spring :
  application:
    name : 05_NETH_MESABOTH_JPA_HIBERNATE_HOMEWORK

  datasource:
    url : jdbc:postgresql://localhost:5432/postgres
    username : postgres
    password : 085760561Both

  jpa :
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
